### ISSUE TITLE
peer to peer code review 22/01/2020

### ISSUE THREAD

**Issue by kbjude** [bx44/eshop-frontend#1]
Beautiful choice of colour

**Comment by moinkhanif** [comment]
Hey Barak, awesome work so far! Here are a few of my observations:

**Comment by moinkhanif** [comment]
Hey Barak, awesome work so far! Here are a few of my observations:

- The text and button in the welcome section can be aligned to the left.
- The footer email button can be given a width of 100%.
- Great use of id for navigation.

Overall it looks great! 👏
